# Generated by Django 5.1.5 on 2025-05-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_no', models.IntegerField()),
                ('half', models.CharField(max_length=50)),
                ('half_other', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Untracked'), (2, 'Sailing'), (3, 'Sunken')], default=0)),
                ('shipped_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=255)),
            ],
        ),
    ]
