# Generated by Django 5.1.5 on 2025-05-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiplist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
