# Generated by Django 5.1.5 on 2025-05-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiplist', '0002_alter_ship_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='half_other_username',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ship',
            name='half_username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
