# Generated by Django 5.1.5 on 2025-05-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiplist', '0003_ship_half_other_username_ship_half_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.FloatField()),
                ('rule_content', models.TextField()),
            ],
        ),
    ]
