# Generated by Django 5.1.5 on 2025-05-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiplist', '0004_rules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rules',
            new_name='Rule',
        ),
    ]
