# Generated by Django 5.1.5 on 2025-05-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiplist', '0005_rename_rules_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='rule_year',
            field=models.IntegerField(default=2020),
        ),
    ]
