# Generated by Django 5.1.5 on 2025-05-27 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiplist', '0006_rule_rule_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='rule_year',
        ),
    ]
