# Generated by Django 5.1.5 on 2025-05-28 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiplist', '0007_remove_rule_rule_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ship',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ships_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ship',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Untracked'), (2, 'Sailing'), (3, 'Sunken')], default=0, help_text="'Pending' is for ships you're not sure about. 'Untracked' is for ghost ships."),
        ),
    ]
