# Generated by Django 5.1.5 on 2025-05-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiplist', '0008_rule_updated_by_ship_updated_by_alter_ship_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='id',
        ),
        migrations.AlterField(
            model_name='ship',
            name='ship_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ship',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Untracked'), (2, 'Sailing'), (3, 'Sunken'), (4, 'Dropped')], default=0, help_text="'Pending' is for ships you're not sure about. 'Untracked' is for ghost ships. 'Dropped' is for discarded ships."),
        ),
    ]
