# Generated by Django 5.1.5 on 2025-05-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiplist', '0009_remove_ship_id_alter_ship_ship_no_alter_ship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='section',
            field=models.IntegerField(choices=[(0, 'CEO Policies'), (1, 'Staff Policies'), (2, 'General Policies')], default=0),
        ),
        migrations.AddField(
            model_name='rule',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
