# Generated by Django 5.1.5 on 2025-06-18 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiplist', '0010_rule_section_rule_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='shipped_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
