# Generated by Django 5.1.5 on 2025-06-18 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiplist', '0011_alter_ship_shipped_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='shipped_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
