# Generated by Django 5.1.5 on 2025-08-10 05:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiplist', '0012_alter_ship_shipped_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ship',
            options={'permissions': [('can_edit_ship_entry', 'Can edit ship entry fields')]},
        ),
        migrations.AlterField(
            model_name='ship',
            name='shipped_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Please use the default time zone +0 (UTC). This is to ensure all ships are in the same timezone.'),
        ),
    ]
